variable "region_name" {}
variable "vpc-cidr_block" {}
variable "vpc_tag" {}
variable "subnet1-cidr_block" {}
variable "subnet1-az" {}
variable "subnet1_tag" {}
variable "subnet2-cidr_block" {}
variable "subnet2-az" {}
variable "subnet2_tag" {}
variable "igw_tag" {}
variable "rt_cidr_block" {}
variable "rt_tag" {}
variable "ec2_az" {}
variable "instance_type" {}
variable "key_name" {}
variable "ec2_tag" {}